import { describe, it } from 'node:test';
import assert from 'node:assert/strict';

import { generateMarkdownReport } from '../../report/markdown.js';
import type { ReportMeta } from '../../report/markdown.js';
import type { RunResult } from '../../runners/playwright/types.js';

const baseMeta: ReportMeta = {
  appId: 'arden-web',
  suite: 'all',
  platform: 'web',
  timestamp: '2026-03-14T10-30-00-000Z',
};

describe('generateMarkdownReport', () => {
  it('should generate a report for all-passing tests', () => {
    const result: RunResult = {
      passed: 2,
      failed: 0,
      skipped: 0,
      timedOut: 0,
      total: 2,
      duration: 3500,
      tests: [
        { id: 'TC-001', title: 'Load home', status: 'passed', duration: 1200 },
        { id: 'TC-002', title: 'Click button', status: 'passed', duration: 2300 },
      ],
    };

    const md = generateMarkdownReport(result, baseMeta);

    assert.ok(md.includes('# Test Report: arden-web'));
    assert.ok(md.includes('ALL PASSED'));
    assert.ok(md.includes('TC-001'));
    assert.ok(md.includes('TC-002'));
    assert.ok(md.includes('PASS'));
    assert.ok(md.includes('3.50s'));
    assert.ok(!md.includes('## Failures'));
  });

  it('should generate a report with failures', () => {
    const result: RunResult = {
      passed: 1,
      failed: 1,
      skipped: 0,
      timedOut: 0,
      total: 2,
      duration: 5000,
      tests: [
        { id: 'TC-001', title: 'Load home', status: 'passed', duration: 2000 },
        {
          id: 'TC-002',
          title: 'Click button',
          status: 'failed',
          duration: 3000,
          error: 'Element not found',
          screenshotPath: '/tmp/screenshot.png',
        },
      ],
    };

    const md = generateMarkdownReport(result, baseMeta);

    assert.ok(md.includes('1 FAILURE(S)'));
    assert.ok(md.includes('## Failures'));
    assert.ok(md.includes('TC-002: Click button'));
    assert.ok(md.includes('Element not found'));
    assert.ok(md.includes('/tmp/screenshot.png'));
  });

  it('should include timed out tests in failures section', () => {
    const result: RunResult = {
      passed: 0,
      failed: 0,
      skipped: 0,
      timedOut: 1,
      total: 1,
      duration: 30000,
      tests: [
        { id: 'TC-001', title: 'Slow test', status: 'timedOut', duration: 30000 },
      ],
    };

    const md = generateMarkdownReport(result, baseMeta);

    assert.ok(md.includes('TIMEOUT'));
    assert.ok(md.includes('## Failures'));
    assert.ok(md.includes('1 FAILURE(S)'));
  });

  it('should format duration correctly', () => {
    const result: RunResult = {
      passed: 1,
      failed: 0,
      skipped: 0,
      timedOut: 0,
      total: 1,
      duration: 500,
      tests: [
        { id: 'TC-001', title: 'Fast test', status: 'passed', duration: 500 },
      ],
    };

    const md = generateMarkdownReport(result, baseMeta);

    assert.ok(md.includes('500ms'));
  });

  it('should include meta information in the header', () => {
    const md = generateMarkdownReport(
      { passed: 0, failed: 0, skipped: 0, timedOut: 0, total: 0, duration: 0, tests: [] },
      { appId: 'fridgify', suite: 'recipe', platform: 'web', timestamp: '2026-03-14T12-00-00' },
    );

    assert.ok(md.includes('fridgify'));
    assert.ok(md.includes('recipe'));
    assert.ok(md.includes('web'));
    assert.ok(md.includes('2026-03-14T12-00-00'));
  });

  it('should include sentinel-qa footer', () => {
    const md = generateMarkdownReport(
      { passed: 0, failed: 0, skipped: 0, timedOut: 0, total: 0, duration: 0, tests: [] },
      baseMeta,
    );

    assert.ok(md.includes('Generated by sentinel-qa'));
  });
});
